apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: container-workshop
    app.kubernetes.io/instance: container-workshop-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  name: container-workshop
spec:
  selector:
    app: container-workshop # matches the pod labels in podTemplate
  type: LoadBalancer  # creates public-facing AWS load-balancer to access the application
  ports:
   -  protocol: TCP
      port: 80  # port that service listens on
      targetPort: http  # container port of to forward traffic to; matches the <ports.name> or <ports.containerPort> field in containerSpec
